name: Run e2e test

on:
  workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        run: npm install

      - name: Start the React app server
        run: |
          npm start &         # Start the server in the background
          sleep 10            # Wait for the server to start (adjust sleep duration if necessary)
        env:
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
     
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: configFile=ci
        env:
            CYPRESS_BASEURL: ${{ secrets.CYPRESS_BASEURL }}
            CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
            CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      
      - name: Stop the React app server
        run: |
          kill $(ps aux | grep '[n]pm start' | awk '{print $2}')
