name: Run e2e test

on:
  workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # Cypress Docker image with Chrome v106
    # and Firefox v106 pre-installed
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - uses: actions/checkout@v3
       
      - name: Install dependencies
        run: npm install
     
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: true
          start: npm start
          browser: chrome
          headed: true
        env:
            REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
            CYPRESS_BASEURL: ${{ secrets.CYPRESS_BASEURL }}
            CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
            CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        continue-on-error: true
      
      - name: Stop the React app server
        run: |
          kill $(ps aux | grep '[n]pm start' | awk '{print $2}')

      - name: Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 

      - name: Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore 
