name: Run e2e test

on:
  workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install
          
      - name: Cypress 
        uses: cypress-io/github-action@v5
        
      - name: Cypress run
        run: |-
          start: npm start
          test: npm run e2e:test
